export enum ApplePayClientStatus {
  SUCCESS = 'SUCCESS',
  CANCEL = 'CANCEL',
  ERROR = 'ERROR',
  CAN_MAKE_PAYMENTS_WITH_ACTIVE_CARD = 'CAN_MAKE_PAYMENTS_WITH_ACTIVE_CARD',
  VALIDATE_MERCHANT_ERROR = 'VALIDATE_MERCHANT_ERROR',
  VALIDATE_MERCHANT_SUCCESS = 'VALIDATE_MERCHANT_SUCCESS'
}
