jsinit_response = {
    'config_tokenisation_visa': 'jsinitTokenisationVisa.json',
    'config_tokenisation_bypass_cards_visa': 'jsinitTokenisationVisa.json',
    'config_tokenisation_visa_request_types': 'jsinitTokenisationVisa.json',
    'config_tokenisation_amex': 'jsinitTokenisationAmex.json',
    'subscription': 'jsinitSubscription.json',
    'start_on_load_sub': 'jsinitStartOnLoadSubscription.json',
    'start_on_load': 'jsinitStartOnLoad.json',
    'immediate_payment': 'jsinitStartOnLoad.json',
    'config_requestTypes_tdq': 'jsinitTDQ.json',
    'config_requestTypes_acheck_tdq_auth': 'jsinitAcheckTdqAuth.json',
    'config_requestTypes_tdq_auth_riskdec': 'jsinitTdqAuthRiskdec.json',
    'config_requestTypes_riskdec_acheck_tdq_auth': 'jsinitRiskdecAcheckTdqAuth.json',
    'config_requestTypes_tdq_submit_on_success': 'jsinitTDQ.json',
    'config_requestTypes_tdq_acheck_riskdec_auth': 'jsinitTdqAcheckRiskdecAuth.json',
    'config_requestTypes_acheck_tdq_auth_subscription': 'jsinitAcheckTdqAuthSub.json',
    'config_immediate_payment_tdq': 'jsinitStartOnLoadTdq.json',
    'config_immediate_payment_tdq_auth': 'jsinitStartOnLoadTdqAuth.json',
    'config_immediate_payment_acheck_tdq_auth': 'jsinitStartOnLoadAcheckTdqAuth.json',
    'config_immediate_payment_riskdec_acheck_tdq_auth': 'jsinitStartOnLoadRiskdecAcheckTdqAuth.json',
}
