### app-html
.build-app-html:
  extends: .utility-images-build
  variables:
    DOCKER_TARGET: 'app-html'
    DOCKERFILE_PATH: docker/app-html/Dockerfile
    USE_PIPELINE_IMAGE: 'true'

build-app-html-test:
  extends: .build-app-html
  variables:
    UTILITY_NAME: 'app-html-test'
    BUILD_ARGS_EXTRA: --build-arg PIPELINE_WORKDIR=/pipeline --build-arg BUILD_TYPE=automated

build-app-html-dev:
  extends: .build-app-html
  variables:
    UTILITY_NAME: 'app-html-dev'
    BUILD_ARGS_EXTRA: --build-arg PIPELINE_WORKDIR=/pipeline --build-arg BUILD_TYPE=dev

### testing repo
build-payments-tests:
  extends: .utility-images-build
  variables:
    UTILITY_NAME: 'payments-tests'
    BUILD_ARGS_EXTRA: --build-arg COPY_FROM=./tests

#### wiremock for testing repo
build-wiremock:
  extends: .utility-images-build
  variables:
    UTILITY_NAME: 'wiremock'
    BUILD_ARGS_EXTRA: --build-arg COPY_FROM=./tests
