.build-sdk:
  extends:
    - .build-with-npm
  variables:
    ARTIFACT_RELEASE_SOURCES: "${CI_PROJECT_DIR}/.releases_sources"
    WEBPACK_CONFIG: 'webpack.prod.js'

build-sdk-review:
  extends:
    - .build-sdk
    - .rules-when-review
  variables:
    EXTRA_ARGS_TEMPLATE: '--frame_url=https://library.securetrading.net:8443'

build-sdk-release:
  extends:
    - .build-sdk
    - .rules-when-release
  variables:
    EXTRA_ARGS_TEMPLATE: '--frame_url=https://cdn.eu.trustpayments.com/js-payments-v3/{RELEASE_TAG}-{CDN_HASH}'

### Other builds

.build-sdk-local:
  extends:
    - .build-with-npm
  variables:
    ARTIFACT_RELEASE_SOURCES: "${CI_PROJECT_DIR}/.local_sources"
    WEBPACK_CONFIG: 'webpack.dev.js'
    EXTRA_ARGS_TEMPLATE: '--frame_url=https://library.securetrading.net:8443'

build-sdk-local-review:
  extends:
    - .build-sdk-local
    - .rules-when-review

build-sdk-local-release:
  extends:
    - .build-sdk-local
    - .rules-when-release

#

.build-sdk-mock:
  extends:
    - .build-with-npm
  variables:
    ARTIFACT_RELEASE_SOURCES: "${CI_PROJECT_DIR}/.mock_sources"
    WEBPACK_CONFIG: 'webpack.mock.js'
    EXTRA_ARGS_TEMPLATE: '--frame_url=https://library.securetrading.net:8443'

build-sdk-mock-review:
  extends:
    - .build-sdk-mock
    - .rules-when-review

build-sdk-mock-release:
  extends:
    - .build-sdk-mock
    - .rules-when-release

