.build-sdk:
  stage: build
  extends:
    - .variables
    - .link_node_modules_before_script
  tags:
    - docker-specific
  image: ${IMAGE_PIPELINE}
  after_script:
    - mkdir -p "${ARTIFACTS_BUILD_PATH}"
    - cp -R "./dist/." "${ARTIFACTS_BUILD_PATH}"
  artifacts:
    when: always
    paths:
      - "${ARTIFACTS_BUILD_PATH}"

build-sdk-local:
  extends: .build-sdk
  variables:
    ARTIFACTS_BUILD_PATH: ".dist-dev"
  script:
    - npm run build:dev --frame_url="https://library.securetrading.net:8443"

build-sdk-mock:
  extends: .build-sdk
  variables:
    ARTIFACTS_BUILD_PATH: ".dist-test"
  script:
    - npm run build:test --frame_url="https://library.securetrading.net:8443"

build-sdk-review:
  extends:
    - .build-sdk
    - .rules-when-review
  variables:
    ARTIFACTS_BUILD_PATH: ".dist-release"
  script:
    - npx lerna bootstrap
    - npx lerna version "0.0.0" --no-git-tag-version --no-push --yes
    - npx lerna run build:prod -- --frame_url="https://cdn.eu.trustpayments.com/js-payments-v3/0.0.0-test"

build-sdk-release:
  extends:
    - .build-sdk
    - .rules-when-release
  variables:
    ARTIFACTS_BUILD_PATH: ".dist-release"
  before_script:
    - . .cicd_scripts/gitlab/release/load_release_artifact.sh "${ARTIFACT_RELEASE_CICD_FILENAME}"
  script:
    - npx lerna bootstrap
    - npx lerna version "${RELEASE_TAG}" --no-git-tag-version --no-push --yes
    - npx lerna run build:prod -- --frame_url="https://cdn.eu.trustpayments.com/js-payments-v3/${RELEASE_TAG}-${CDN_HASH}"
