import { ICorrelatedMaskedCard } from '../digital-terminal/interfaces/ICorrelatedMaskedCard';
import { SrcName } from '../digital-terminal/SrcName';

export const cardListMock: ICorrelatedMaskedCard[] = [
  {
    srcCorrelationId: '001',
    idToken: '001',
    srcName: SrcName.VISA,
    isActive: true,
    srcDigitalCardId: '001',
    panBin: '001',
    panLastFour: 6263,
    tokenBinRange: '',
    paymentAccountReference: '',
    tokenLastFour: 6263,
    panExpirationMonth: 8,
    panExpirationYear: 2022,
    digitalCardData: {
      status: 'ACTIVE',
      artUri: 'card001Url',
      artHeight: 40,
      artWidth: 60,
    },
    dateofCardCreated: 1,
    dateofCardLastUsed: 2,
    dcf: {
      uri: '',
      logoUri: '',
      name: '',
    },
    maskedBillingAddress: {
      addressId: '',
      line1: '',
      line2: '',
      line3: '',
      city: '',
      state: '',
      zip: '',
      countryCode: '',
      createTime: '',
      lastUsedTime: 3,
    },
  },
  {
    srcCorrelationId: '002',
    idToken: '002',
    srcName: SrcName.VISA,
    isActive: false,
    srcDigitalCardId: '002',
    panBin: '002',
    panLastFour: 1345,
    tokenBinRange: '',
    paymentAccountReference: '',
    tokenLastFour: 1345,
    panExpirationMonth: 8,
    panExpirationYear: 2022,
    digitalCardData: {
      status: 'ACTIVE',
      artUri: 'card002Url',
      artHeight: 40,
      artWidth: 60,
    },
    dateofCardCreated: 1,
    dateofCardLastUsed: 2,
    dcf: {
      uri: '',
      logoUri: '',
      name: '',
    },
    maskedBillingAddress: {
      addressId: '',
      line1: '',
      line2: '',
      line3: '',
      city: '',
      state: '',
      zip: '',
      countryCode: '',
      createTime: '',
      lastUsedTime: 3,
    },
  },
  {
    srcCorrelationId: '003',
    idToken: '003',
    srcName: SrcName.VISA,
    isActive: false,
    srcDigitalCardId: '003',
    panBin: '003',
    panLastFour: 1234,
    tokenBinRange: '',
    paymentAccountReference: '',
    tokenLastFour: 1234,
    panExpirationMonth: 8,
    panExpirationYear: 2022,
    digitalCardData: {
      status: 'ACTIVE',
      artUri: 'card003Url',
      artHeight: 40,
      artWidth: 60,
    },
    dateofCardCreated: 1,
    dateofCardLastUsed: 2,
    dcf: {
      uri: '',
      logoUri: '',
      name: '',
    },
    maskedBillingAddress: {
      addressId: '',
      line1: '',
      line2: '',
      line3: '',
      city: '',
      state: '',
      zip: '',
      countryCode: '',
      createTime: '',
      lastUsedTime: 3,
    },
  },
  {
    srcCorrelationId: '004',
    idToken: '004',
    srcName: SrcName.VISA,
    isActive: true,
    srcDigitalCardId: '004',
    panBin: '004',
    panLastFour: 4885,
    tokenBinRange: '',
    paymentAccountReference: '',
    tokenLastFour: 4885,
    panExpirationMonth: 8,
    panExpirationYear: 2022,
    digitalCardData: {
      status: 'ACTIVE',
      artUri: 'card004Url',
      artHeight: 40,
      artWidth: 60,
    },
    dateofCardCreated: 1,
    dateofCardLastUsed: 2,
    dcf: {
      uri: '',
      logoUri: '',
      name: '',
    },
    maskedBillingAddress: {
      addressId: '',
      line1: '',
      line2: '',
      line3: '',
      city: '',
      state: '',
      zip: '',
      countryCode: '',
      createTime: '',
      lastUsedTime: 3,
    },
  },
];
