#################################### Security ZAP scan ###################################
.zap-url-to-scan-merchant:
  variables:
    URL_TO_SCAN: "https://merchant.securetrading.net"

.zap-url-to-scan-library:
  variables:
    URL_TO_SCAN: "https://library.securetrading.net:8443"

merchant-securetrading-net-review-security-tests-zap-baseline-scan:
  extends:
    - .zap-baseline-scan
    - .services-app-html-review
    - .zap-url-to-scan-merchant
    - .rules-when-review
  variables:
    ZAP_CONFIG_PATH: "baseline-scan.conf"

library-securetrading-net-review-security-tests-zap-baseline-scan:
  extends:
    - .zap-baseline-scan
    - .services-app-html-review
    - .zap-url-to-scan-library
    - .rules-when-review
  variables:
    ZAP_CONFIG_PATH: "baseline-scan.conf"

merchant-securetrading-net-release-security-tests-zap-baseline-scan:
  extends:
    - .zap-baseline-scan
    - .service-app-html-release-merchant
    - .zap-url-to-scan-merchant
    - .rules-when-release
  variables:
    ZAP_CONFIG_PATH: "baseline-scan.conf"

scan-library-securetrading-net-release-security-tests-zap-baseline-scan:
  extends:
    - .zap-baseline-scan
    - .service-app-html-release-library
    - .zap-url-to-scan-library
    - .rules-when-release
  variables:
    ZAP_CONFIG_PATH: "baseline-scan.conf"
