export enum APMName {
  BITPAY = 'BITPAY',
  GIROPAY = 'GIROPAY',
  EPS = 'EPS',
  IDEAL = 'IDEAL',
  MYBANK = 'MYBANK',
  PAYU = 'PAYU',
  POSTFINANCE = 'POSTFINANCE',
  PRZELEWY24 = 'PRZELEWY24',
  UNIONPAY = 'UNIONPAY',
  ZIP = 'ZIP',
}
