export enum ApplePayClientErrorCode {
  NO_ACTIVE_CARDS_IN_WALLET = 4,
  CAN_MAKE_PAYMENTS_WITH_ACTIVE_CARD = 5,
  VALIDATE_MERCHANT_SUCCESS = 6,
  VALIDATE_MERCHANT_ERROR = 7,
  ON_VALIDATE_MERCHANT = 8,
  ON_PAYMENT_AUTHORIZED = 9,
  EMPTY_JWT_ERROR = 10,
  ERROR = 1,
  CANCEL = 2,
  SUCCESS = 0,
  DECLINE = 70000
}
