version: "3.6"
services:
  app-html:
    build:
      args:
        BUILD_TYPE: "mock"

  wiremock:
    build:
      context: ../..
      dockerfile: ./docker/wiremock/Dockerfile
      target: wiremock
      args:
        COPY_FROM: ./tests
    volumes:
      - ../../tests/wiremock/__files:/home/wiremock/__files
      - ../../tests/wiremock/mappings:/home/wiremock/mappings
      - ../../tests/wiremock/keystore:/home/wiremock/keystore
    command: --https-port 6443 --https-keystore /home/wiremock/keystore --verbose
    ports:
      - 6443:6443
    networks:
      securetrading:
        aliases:
          - webservices.securetrading.net
          - thirdparty.example.com
