version: "3.6"
services:
  app-html:
    build:
      context: ../..
      dockerfile: ./docker/app-html/Dockerfile
      target: app-html
      args:
        SDK_DIST_PATH: "dist"
        APP_DIST_PATH: "example/html/dist"
    ports:
      - 80:80
      - 443:443
      - 8443:8443
    networks:
      securetrading:
        aliases:
          - library.securetrading.net
          - merchant.securetrading.net

  payments-tests:
    build:
      context: ../..
      dockerfile: ./docker/payments_tests/Dockerfile
      target: payments-tests
      args:
        COPY_FROM: "./tests"
        IMAGE_PIPELINE: "${CI_REGISTRY_IMAGE}/pipeline:master"
    volumes:
      - ../../tests/features:/app/features
      - ../../tests/locators:/app/locators
      - ../../tests/mappings:/app/mappings
      - ../../tests/modules:/app/modules
      - ../../tests/pages:/app/pages
      - ../../tests/resources:/app/resources
      - ../../tests/utils:/app/utils
    networks:
      - securetrading

networks:
  securetrading:
    driver: bridge
