from enum import Enum


class ConfigApm(Enum):
    BASIC_CONFIG_APM = 'e2eBasicConfigApm.json'
    ATA_CONFIG_APM = 'e2eATAConfigApm.json'
    BANCONTACT_CONFIG_APM = 'e2eBANCONTACTConfigApm.json'
    BITPAY_CONFIG_APM = 'e2eBITPAYConfigApm.json'
    GIROPAY_CONFIG_APM = 'e2eGIROPAYConfigApm.json'
    EPS_CONFIG_APM = 'e2eEPSConfigApm.json'
    IDEAL_CONFIG_APM = 'e2eIDEALConfigApm.json'
    MULTIBANCO_CONFIG_APM = 'e2eMULTIBANCOConfigApm.json'
    MYBANK_CONFIG_APM = 'e2eMyBankConfigApm.json'
    PAYU_CONFIG_APM = 'e2ePayUConfigApm.json'
    POSTFINANCE_CONFIG_APM = 'e2ePOSTFINANCEConfigApm.json'
    PRZELEWY24_CONFIG_APM = 'e2ePRZELEWY24ConfigApm.json'
    SOFORT_CONFIG_APM = 'e2eSOFORTConfigApm.json'
    SEPADD_CONFIG_APM = 'e2eSEPADDConfigApm.json'
    TRUSTLY_CONFIG_APM = 'e2eTRUSTLYConfigApm.json'
    REDPAGOS_CONFIG_APM = 'e2eREDPAGOSConfigApm.json'
    SAFETYPAY_CONFIG_APM = 'e2eSAFETYPAYConfigApm.json'
    WECHATPAY_CONFIG_APM = 'e2eWECHATPAYConfigApm.json'
    UNIONPAY_CONFIG_APM = 'e2eUNIONPAYConfigApm.json'
    ZIP_CONFIG_APM = 'e2eZIPConfigApm.json'
    ZIP_MIN_MAX_CONFIG_APM = 'e2eZIPminMaxConfigApm.json'
